[package]
name = "signum"
version = "0.1.0"
authors = ["Xiphoseer <xiphoseer@mailbox.org>"]
edition = "2018"

[dependencies]
nom = "6.1.0"
thiserror = "1.0"
bitflags = "1.2"
ccitt-t4-t6 = { path = "../ccitt" }

[dependencies.image]
default-features = false
version = "0.23"
features = ["png"]