# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          working-directory: ./docs
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build the Studio
        working-directory: ./crates/sdo-web
        run: wasm-pack build --target web
      - name: Run rustdoc
        run: cargo doc --no-deps --workspace --lib
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Create output dir with permissions
        run: mkdir ${{ github.workspace }}/_site
      - name: Build with Jekyll
        run: >
          bundle exec jekyll build
          --baseurl "${{ steps.pages.outputs.base_path }}"
          --destination "${{github.workspace}}/_site"
        working-directory: ./docs
        env:
          JEKYLL_ENV: production
      - name: Copy files to site
        run: |
          mkdir ./_site/studio
          cp -r ./crates/sdo-web/pkg ./_site/studio/
          cp ./crates/sdo-web/index.html ./_site/studio
          cp ./crates/sdo-web/index.mjs ./_site/studio
          cp -r ./target/doc ./_site/rustdoc
          mkdir ./_site/pub
          cp -r ./mappings ./_site/pub/mappings
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
