name: Release Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'mappings/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest
    
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]

    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo target dir
      if: matrix.os != 'macOS'
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
      if: github.ref == 'refs/heads/main'
    - name: Upload files (windows)
      uses: actions/upload-artifact@v4
      if: matrix.os == 'windows' && github.ref == 'refs/heads/main'
      with:
        name: sdo-toolbox-windows
        path: |
          target/release/sdo-tool.exe
          target/release/chset-kb.exe
          target/release/dvips-font.exe
          target/release/sdo-batch.exe
          target/release/signum-file.exe
          target/release/st-decode.exe
    - name: Upload files (*nix)
      uses: actions/upload-artifact@v4
      if: matrix.os != 'windows' && github.ref == 'refs/heads/main'
      with:
        name: sdo-toolbox-${{ matrix.os }}
        path: |
          target/release/sdo-tool
          target/release/chset-kb
          target/release/dvips-font
          target/release/sdo-batch
          target/release/signum-file
          target/release/st-decode