name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest
    
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      if: ${{ matrix.os }} == 'windows'
      with:
        name: sdo-tool-windows.exe
        path: target/debug/sdo-tool.exe
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      if: ${{ matrix.os }} != 'windows'
      with:
        name: sdo-tool-${{ matrix.os }}
        path: target/debug/sdo-tool
